// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVufnY8UT15fR7XCnzV52-9Icv-vGJYOE',
    appId: '1:362107388745:web:0303e5a48dc8ad15631098',
    messagingSenderId: '362107388745',
    projectId: 'ai-notes-e1775',
    authDomain: 'ai-notes-e1775.firebaseapp.com',
    storageBucket: 'ai-notes-e1775.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjqATP-u3wlwxIYfcg9hKcwRem46YJOH4',
    appId: '1:362107388745:android:8ec5fa1953ce56b0631098',
    messagingSenderId: '362107388745',
    projectId: 'ai-notes-e1775',
    storageBucket: 'ai-notes-e1775.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSuJMLUwzxxxpZB1xXfXC1qQqo3G3ZRXQ',
    appId: '1:362107388745:ios:769b0d3800e48f94631098',
    messagingSenderId: '362107388745',
    projectId: 'ai-notes-e1775',
    storageBucket: 'ai-notes-e1775.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSuJMLUwzxxxpZB1xXfXC1qQqo3G3ZRXQ',
    appId: '1:362107388745:ios:769b0d3800e48f94631098',
    messagingSenderId: '362107388745',
    projectId: 'ai-notes-e1775',
    storageBucket: 'ai-notes-e1775.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVufnY8UT15fR7XCnzV52-9Icv-vGJYOE',
    appId: '1:362107388745:web:2733d007247647e2631098',
    messagingSenderId: '362107388745',
    projectId: 'ai-notes-e1775',
    authDomain: 'ai-notes-e1775.firebaseapp.com',
    storageBucket: 'ai-notes-e1775.firebasestorage.app',
  );
}
